### ISSUE TITLE
Re-design Static Array

### ISSUE THREAD

**Issue by sombeam** [sorgom/DSTW#45]
The StaticArray class has too many options.

Create dedicated classes:

**InterfaceArray**
- not sortable
- main class virtual
- add of derived class
- non const access

**FixedDataArray**
- not sortable
 - const access only
 - only main class
 
**Index**
- refers FixedDataArray
- is sortable
- virtual is greater

**Comment by sorgom** [comment]
OK

- InterfaceArray: InterfaceArray
- FixedDataArray: ConstArray
- Index: ConstArrayIndex

**Comment by sombeam** [comment]
looks good.
